[package]
name = "datakiste"
version = "0.10.0"
authors = ["Justin Browne <brownej@nscl.msu.edu>"]
edition = "2018"

[dependencies]
byteorder = "*"
rand = "*"
val_unc = { git = "https://github.com/j-browne/val_unc" }
