[package]
name = "datakiste"
version = "0.9.0"
authors = ["Justin Browne <brownej@nscl.msu.edu>"]
edition = "2018"

[dependencies]
byteorder = "0.5.2"
rand = "0.3.14"
val_unc = { path = "../val_unc/" }
